using System.Collections.Generic;
using System.Linq;
using UnityEngine;
using UnityEngine.Experimental.Rendering.Universal;


// Credit for ThundThund for ShadowCaster2DExtensions
/// <summary>
/// Creates a Shadow Caster 2D to the gameobject if a supported Collider 2D is found.
/// Supported colliders are PolygonCollider2D and CompositeCollider2D.
/// </summary>
public class AutomaticShadowCaster2D : MonoBehaviour
{
    public bool generateSelfShadows = true;
    
    private void Awake()
    {
        // Find a supported collider type
        if (TryGetComponent(out PolygonCollider2D polygonCollider2D))
        {
            var pointsInPath3D = new Vector3[polygonCollider2D.points.Length];
            
            // Convert Vector2[] to Vector3[]
            for (int j = 0; j < polygonCollider2D.points.Length; ++j)
            {
                pointsInPath3D[j] = polygonCollider2D.points[j]; 
            }
            
            var shadowCaster2D = gameObject.AddComponent<ShadowCaster2D>();
            
            shadowCaster2D.selfShadows = generateSelfShadows;
            
            // Shadow caster 2D has horrible support. Use extensions to define the shape
            shadowCaster2D.SetPath(pointsInPath3D.ToArray());
            shadowCaster2D.SetPathHash(Random.Range(int.MinValue, int.MaxValue)); // Hash set initiates internal recalculation of shadows
        }
        
        else if (TryGetComponent(out CompositeCollider2D compositeCollider2D))
        {
            // Create the new shadow casters, based on the paths of the composite collider
            int pathCount = compositeCollider2D.pathCount;
            List<Vector2> pointsInPath = new List<Vector2>();
            List<Vector3> pointsInPath3D = new List<Vector3>();

            for (int i = 0; i < pathCount; ++i)
            {
                compositeCollider2D.GetPath(i, pointsInPath);

                var newGameObject = new GameObject("ShadowCaster2D") {isStatic = true};
                newGameObject.transform.SetParent(compositeCollider2D.transform, false);
                
                for (int j = 0; j < pointsInPath.Count; ++j)
                {
                    pointsInPath3D.Add(pointsInPath[j]);
                }

                var shadowCaster2D = newGameObject.gameObject.AddComponent<ShadowCaster2D>();
                
                shadowCaster2D.selfShadows = generateSelfShadows;
                
                // Shadow caster 2D has horrible support. Use extensions to define the shape
                shadowCaster2D.SetPath(pointsInPath3D.ToArray());
                shadowCaster2D.SetPathHash(Random.Range(int.MinValue,
                    int.MaxValue)); // The hashing function GetShapePathHash could be copied from the LightUtility class

                pointsInPath.Clear();
                pointsInPath3D.Clear();
            }
        }
        else
        {
            Debug.LogWarning("Collider type not supported for " + gameObject.name);
        }
    }

    /// <summary>
    /// Gives access to the ShadowCaster2D generated by this script. Note, if you try to use this with a
    /// CompositeCollider2D, it will only return the first one.
    /// </summary>
    public ShadowCaster2D GeneratedShadowCaster2D => this.gameObject.GetComponent<ShadowCaster2D>();
    
    /// <summary>
    /// Gives access to an array of ShadowCaster2D's generated by this script. This is to support CompositeCollider2D scripting.
    /// </summary>
    public ShadowCaster2D[] GeneratedShadowCaster2Ds => this.gameObject.GetComponents<ShadowCaster2D>();
}
